CURRENCIES = {
    1: 'Orb of Alteration',
    2: 'Orb of Fusing',
    3: 'Orb of Alchemy',
    4: 'Chaos Orb',
    5: "Gemcutter's Prism",
    6: 'Exalted Orb',
    7: 'Chromatic Orb',
    8: "Jeweller's Orb",
    9: 'Orb of Chance',
    10: "Cartographer's Chisel",
    11: 'Orb of Scouring',
    12: 'Blessed Orb',
    13: 'Orb of Regret',
    14: 'Regal Orb',
    15: 'Divine Orb',
    16: 'Vaal Orb',
    17: 'Scroll of Wisdom',
    18: 'Portal Scroll',
    19: "Armourer's Scrap",
    20: "Blacksmith's Whetstone",
    21: "Glassblower's Bauble",
    22: 'Orb of Transmutation',
    23: 'Orb of Augmentation',
    24: 'Mirror of Kalandra',
    25: 'Eternal Orb',
    26: 'Perandus Coin',
    27: 'Sacrifice at Dusk',
    28: 'Sacrifice at Midnight',
    29: 'Sacrifice at Dawn',
    30: 'Sacrifice at Noon',
    31: 'Mortal Grief',
    32: 'Mortal Rage',
    33: 'Mortal Hope',
    34: 'Mortal Ignorance',
}

POE_CURRENCY_COUNT = len(CURRENCIES.keys())