# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-04 00:00
from __future__ import unicode_literals

from django.db import migrations
from core.constants import CURRENCIES
from trades.models import Currency

def create_lookup_table(apps, *_, **__):
    currencies = []
    for k in CURRENCIES:
        currencies.append(Currency(id=k, name=CURRENCIES[k]))

    Currency.objects.bulk_create(currencies)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_lookup_table)
    ]
